### PR TITLE
Some improvements to the python bindings

### PR DESCRIPTION
**Pull request by michaelnt**
Added some doc strings.

Added a setup.py so that the module can be installed in a virtualenv and no longer needs sudo access.

Added some unittests.

### CODE REVIEW

**Comment by michaelnt** [comment]
Tried installing this with pip to another repo and this was what I needed to do, so still needs a little work.

virtualenv py27
. py27/bin/activate
pip install -e git+git://github.com/michaelnt/libpsf.git@binding-docstrings#egg=libpsf
cd py27/src/libpsf
./autogen.sh --with-python
make install
pip install -e git+git://github.com/michaelnt/libpsf.git@binding-docstrings#egg=libpsf
cd ../../lib
export LD_LIBRARY_PATH=`pwd`

**Comment by henjo** [comment]
Hi Michael,

Thanks for the contribution, I haven't used "pip" before but it looks really handy to be able to install a python package directly from a git repo.

I have a build problem though when building with python bindings:

make[1]: Entering directory `/tmp/libpsf/src'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/tmp/libpsf/src'
Making all in include
make[1]: Entering directory`/tmp/libpsf/include'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory`/tmp/libpsf/include'
Making all in bindings
make[1]: Entering directory `/tmp/libpsf/bindings'
Making all in python
make[2]: Entering directory`/tmp/libpsf/bindings/python'
/usr/bin/python setup.py build
/usr/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory
make[2]: **\* [all-local] Error 2
make[2]: Leaving directory `/tmp/libpsf/bindings/python'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/tmp/libpsf/bindings'
make: **\* [all-recursive] Error 1

The automake makefile in bindings/python seems to expect a setup.py there.

/Henrik

**Comment by michaelnt** [comment]
Sorry the last commit was an attempt to make the library pip installable but it didn't work. pip expects there to be a setup.py in the root of the repo, but at the moment the setup.pt is generated by autogen.sh from setup.py.in. This could be generated as part of building a release. But the second problem is that the setup.py doesn't build the libpsf library that the python bindings have to link to.

You could merge just the first three commits, and distribute the c library separately from the python bindings. To use the libraary you first must install libpsf and can then pip (easy_install) install pylibpsf.

I can also pull the last commit of this branch if you want.

**Comment by michaelnt** [comment]
I dropped the commit that placed setup.py in the root dir.

I have added a commit which changes setup.py so that it is run time configurable, rather than using autoconf.

The python module can now be build as.

cd bindings/python
python setup.py build_ext --boost=/proj/libs/releases/boost/1.48.0 --libpsf=/proj/libs/users/michaelt/WORK/py27/

**Comment by henjo** [comment]
Yesterday I tried autogen.sh --with-python which now calls setup.py, and it almost works. The problem is that distutil expects that libpsf is already installed so if one would change Makefile.am and add --libpsf=../.. it might work.

**Comment by michaelnt** [comment]
You can now build the python binding by running make in the top dir.

Turns out build_ext already has options to specify the library include dir, so I removed the --libpsf and --boost options.

**Comment by henjo** [comment]
Great, I added prefix and root install options as well that was needed to build the debs

**Pull request merged**
